### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by damnedest** [zendframework/zend-mail#62]
Class 'Zend\ServiceManager\AbstractPluginManager' not found in vendor/zendframework/zend-mail/src/Protocol/SmtpPluginManager.php on line 20

**Comment by gianarb** [comment]
Hello

It is a suggested class https://github.com/zendframework/zend-mail/blob/master/composer.json#L30 .

Why is suggested and not required?
Mystery..

**Comment by weierophinney** [comment]
It's a *suggested* package as the SMTP implementation is opt-in; many (most?) developers tend to use the default Sendmail protocol implementation when using zend-mail, and we do not want to add another dependency for the default use case. The SMTP protocol requires servicemanager capabilities as there are a number of backends possible (mainly due to authorization differences).

If you need the SMTP functionality:

```console
$ composer require zendframework/zend-servciemanager
```
